=== wwagner4/wodka/doc/greenwood.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="a">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="href" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="chapter">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="content"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="content">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="ul" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="p" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="table" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="greenwood">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="parameters"/>
                <xs:element ref="title"/>
                <xs:element ref="page" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="li">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="a"/>
                <xs:element ref="img"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="p">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="a"/>
                <xs:element ref="img"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="page">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="chapter" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="parameter">
        <xs:complexType>
            <xs:attribute name="name" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="background-color"/>
                        <xs:enumeration value="color"/>
                        <xs:enumeration value="border-color"/>
                        <xs:enumeration value="font-family"/>
                        <xs:enumeration value="font-size"/>
                        <xs:enumeration value="font-size-big"/>
                        <xs:enumeration value="link-color"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="value" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="parameters">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="parameter" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="table">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="tr" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="td">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="a"/>
                <xs:element ref="img"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="th" type="xs:string"/>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="tr">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="th" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="td" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="ul">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="li" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="img">
        <xs:complexType>
            <xs:attribute name="src" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== wwagner4/wodka/doc/greenwood.xml
<?xml version="1.0" encoding="UTF-8"?>
<greenwood xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="greenwood.xsd">
    <parameters>
        <parameter name="font-family" value="'Lucida Sans', 'Arial', sans-serif"/>
        <parameter name="font-size" value="15px"/>
        <parameter name="font-size-big" value="20px"/>
        <parameter name="background-color" value="#000000"/>
        <parameter name="color" value="#fdffe3"/>
        <parameter name="link-color" value="#faffab"/>
        <parameter name="border-color" value="#faffab"/>
    </parameters>
    <title>wodka</title>
    <page name="index">
        <title>home</title>
        <chapter name="goal">
            <title>goal</title>
            <content>
                <p>Wodka is the implementation of a genetic algorithm for breeding soda robots. It is designed as platform that allows configuration
                        of the genetic algorithm in an easy and flexible way. </p>
                <p>The idea is that wodka provides the infrastructure that is needed to breed soda robots, to allow you focusing on your ideas without
                        having to think about technical details.
                </p>
            </content>
        </chapter>
        <chapter name="features">
            <title>features</title>
            <content>
                <ul>
                    <li>Interface for implementing different genetic representations (genotypes) of soda robots.</li>
                    <li>Interface for implementing different selection strategies.</li>
                    <li>Java class representation of soda models.</li>
                    <li>Racer classes for easily testing models on the soda race application.</li>
                    <li>Persistence layer for saving and reloading the genetic algorithm at any state of evaluation.</li>
                    <li>Export functionality to generate race xml's for the soda race application that illustrate the 
                                    evolution of your models.</li>
                    <li>Parameterization of all attributes by means of a parameterization interface.</li>
                </ul>
                <p>planned</p>
                <ul>
                    <li>Implementation of new phenotypes and selection strategies.</li>
                    <li>Distributed evaluation, by means of vgrid</li>
                </ul>
            </content>
        </chapter>
        <chapter name="examples">
            <title>examples</title>
            <content>
				<p>Click one of the following links to start an example.</p>
				<p> 
					<a href="race_d.jnlp">Walking lance</a>, 
					<a href="race_e.jnlp">Walking heap</a>, 
					<a href="race_c.jnlp">Fast triangles on flat terrain</a>, 
					<a href="race_f.jnlp">Pushing triangles</a>
				</p>
				<p> 
					<a href="race_a.jnlp">Flying heaps in difficult terrain</a>, 
					<a href="race_b.jnlp">Pushing triangles that fail to overcome a very narrow hill</a>, 
				</p>
            </content>
        </chapter>
        <chapter name="contact">
            <title>contact</title>
            <content>
                <p>Wolfgang Wagner</p>
                <p>Vienna/Austria</p>
                <p>email: wolfgang.wagner@iname.com</p>
            </content>
        </chapter>
        <chapter name="links">
            <title>links</title>
            <content>
                <table>
                    <tr>
                        <td>
                            <a href="http://www.sourceforge.net">sourceforge</a>
                        </td>
                        <td>
                            <img src="http://sourceforge.net/sflogo.php?group_id=wodka&amp;type=1" />
                        </td>
                        <td>This site is hosted by sourceforge. A great place for open source.</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="http://sodarace.net">sodarace</a>
                        </td>
                        <td></td>
                        <td>Sodarace is the online olympics pitting human creativity against machine learning in a 
                                competition to design robots that race over 2D terrains using the Soda constructor.</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="http://sourceforge.net/forum/forum.php?forum_id=213078">help forum</a>
                        </td>
                        <td></td>
                        <td>If you have any questions concerning wodka you may find the answer here. If you do not find
                        the answer feel free to ask. Stupid questions welcome.</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="http://sourceforge.net/forum/forum.php?forum_id=213077">discussion forum</a>
                        </td>
                        <td></td>
                        <td>Any topic concerning wodka might be discussed here.</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="http://sourceforge.net/projects/wodka/">Project Summary</a>
                        </td>
                        <td></td>
                        <td>All about the development of wodka.</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="jd/index.html">jjavadoc</a>
                        </td>
                        <td></td>
                        <td>Javadoc for the wodka source code.</td>
                    </tr>
                </table>
				<p>Some other projects of mine:</p>
				<table>
                    <tr>
                        <td><a href="http://wodka.sf.net/gimage">gimage</a></td>
                        <td>Genetical images</td>
                        <td>The artistic branch of wodka. Images are generated by genetic algorithms. The fitnesfunction is your taste.</td>
                    </tr>
                    <tr>
                        <td><a href="http://vgrid.sf.net">vgrid</a></td>
                        <td>The vienna grid project</td>
                        <td>A General purpose java based grid framework. One day wodka will run as distributed application.</td>
                    </tr>
                    <tr>
                        <td><a href="http://vsoc.sf.net">vsoc</a></td>
                        <td>Virtual soccer</td>
                        <td>A project that breeds soccer playing robots for the soccer server simulation league. Uses neuronal nets and 
							genetic algorithms.</td>
                    </tr>
                    <tr>
                        <td><a href="http://atan1.sf.net">atan</a></td>
                        <td></td>
                        <td>A java interface for the soccer server simulation league.</td>
                    </tr>
                </table>
            </content>
        </chapter>
    </page>
    <page name="installation">
        <title>download / installation</title>
        <chapter name="prereqs">
            <title>prerequisites</title>
            <content>
                <p>Wodka is a java application.To run it you need the java virtual machine on your computer. If you
                have a Mac you are lucky as it is already installed. The others can get it from <a href="http://java.com">java.com</a> for free.</p>
                <p>You need version 1.4 or higher.</p>
                <p>Test it by typing in a commandline window (console) 'java -version'. The result should be something like 
                'java version 1.5.0_02 Java (TM) 2 RuntimeEnvironment...'</p>
            </content>
        </chapter>

        <chapter name="webstart">
            <title>java webstart</title>
            <content>
                <p>You can start the wodka breeder directly by klicking the following links:</p>
                <p>
                    <a href="Breeder.jnlp">Run the Breeder</a>
                </p>
                <p>
                    <a href="Genolab.jnlp">Run the Geno Lab</a>
                </p>
            </content>
        </chapter>


        <chapter name="download">
            <title>download</title>
            <content>
                <p>Download the the latest wodka release from the wodka 
                <a href="http://sourceforge.net/project/showfiles.php?group_id=63128">download page</a>
                 .The name is wodka vx.x (e.g. wodka v0.22).</p>
                <p>One release consists usually of a single zip file that contains executables, libraries and source code.</p>
            </content>
        </chapter>
        <chapter name="install">
            <title>installation</title>
            <content>
                <ul>
                    <li>Expand the downloaded zip file anywhere on your computer. E.g. to 'c:\Program Files' or '/usr/local/'</li>
                    <li>If you run wodka under linux you will have to generate your own script files to start wodka. Take the
                    .bat files in the /bin/ directory as a template. As wodka uses a java invoker the changes should be minimal.</li>
                </ul>
            </content>
        </chapter>
    </page>
    <page name="uguide">
        <title>user guide</title>
        <chapter name="admindir">
            <title>the admin directory</title>
            <content>
				<p>Whenever you start any of the wodka applications the first time a wodka directory is generated in your user home directory. Within the
					wodka directory an admin directory is created that holds a wodka.properties fle. This file will be the main source for configuration for
					all wodka applications in the future. Detailed infos about the properties can be found in the properties file itself.</p>
			</content>
		</chapter>
